"""initial_schema

Revision ID: 90a256fa371c
Revises: 
Create Date: 2026-03-14 12:25:27.284433
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a256fa371c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('server_url', sa.String(length=500), nullable=False),
    sa.Column('transport_type', sa.String(length=20), nullable=False),
    sa.Column('auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tools_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_platforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_enc', sa.LargeBinary(), nullable=True),
    sa.Column('api_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('market_hours', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_analysis_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_provider_id', sa.UUID(), nullable=True),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('bid', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('ask', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('ai_recommendation', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('trade_action', sa.String(length=10), nullable=False),
    sa.Column('lot_size', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('tp_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['trading_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_log_ai_provider_id'), 'ai_analysis_log', ['ai_provider_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_log_created_at'), 'ai_analysis_log', ['created_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('bot_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['trading_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_events_created_at'), 'bot_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_events_event_type'), 'bot_events', ['event_type'], unique=False)
    op.create_table('bot_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('max_trades_per_day', sa.Integer(), nullable=False),
    sa.Column('risk_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sl_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tp_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pause_max_retries', sa.Integer(), nullable=False),
    sa.Column('pause_retry_sec', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['trading_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('lot', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('sl_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('tp_price', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('profit', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('commission', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('swap', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ai_provider_id', sa.UUID(), nullable=True),
    sa.Column('ai_analysis_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['ai_providers.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['trading_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_platform_id'), 'trades', ['platform_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_platform_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_table('bot_settings')
    op.drop_index(op.f('ix_bot_events_event_type'), table_name='bot_events')
    op.drop_index(op.f('ix_bot_events_created_at'), table_name='bot_events')
    op.drop_table('bot_events')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_analysis_log_created_at'), table_name='ai_analysis_log')
    op.drop_index(op.f('ix_ai_analysis_log_ai_provider_id'), table_name='ai_analysis_log')
    op.drop_table('ai_analysis_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trading_platforms')
    op.drop_table('mcp_connections')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
